export const CATEGORY_ACTION_TYPES = Object.freeze({
  ADD__CATEGORY: '[CATEGORY] - ADD__CATEGORY',
  DELETE__CATEGORY: '[CATEGORY] - DELETE__CATEGORY',
  RENAME__CATEGORY: '[CATEGORY] - RENAME__CATEGORY',
  ADD__TASK: '[CATEGORY] - ADD__TASK',
  DELETE__TASK: '[CATEGORY] - DELETE__TASK',
  
});
