export const CATEGORY_ACTION_TYPES = Object.freeze({
  ADD__CATEGORY: '[CATEGORY] - ADD__CATEGORY',
  DELETE__CATEGORY: '[CATEGORY] - DELETE__CATEGORY',
  RENAME__CATEGORY: '[CATEGORY] - RENAME__CATEGORY',
});
