export const CATEGORY_ACTION_TYPES = Object.freeze({
  ADD__CATEGORY: '[CATEGORY] - ADD__CATEGORY',
  DELETE__CATEGORY: '[CATEGORY] - DELETE__CATEGORY',
  RENAME__CATEGORY: '[CATEGORY] - RENAME__CATEGORY',
  SHOW__CATEGORY: '[CATEGORY] - SHOW__CATEGORY',
  
  ADD__TASK: '[CATEGORY] - ADD__TASK',
  TOGGLE__TASK: '[CATEGORY] - TOGGLE__TASK' , 
  RENAME__TASK: '[CATEGORY] - RENAME__TASK',
  DELETE__TASK: '[CATEGORY] - DELETE__TASK',
});
